# Minimal cursedboard configuration
# Both sides now act as client and server simultaneously

[network]
bind_addr = "0.0.0.0"  # Listen on all interfaces
port = 34254

# Add peers to connect to
[[network.peers]]
host = "172.16.104.129"
# port = 34254  # Optional, defaults to same as local port