# Complete configuration example for macOS
# Place this file at ~/.config/cursedboard/config.toml

[network]
bind_addr = "0.0.0.0"  # Listen for incoming connections
port = 34254
connection_timeout = "10s"

# Define peers to connect to
[[network.peers]]
host = "172.16.104.129"  # Linux machine IP
name = "linux-desktop"   # Optional friendly name

# Add more peers as needed
# [[network.peers]]
# host = "192.168.1.101"
# port = 34255  # Different port if needed
# name = "other-mac"

[network.reconnect]
enabled = true
initial_delay = "1s"
max_delay = "60s"
# max_attempts = 10  # Uncomment to limit reconnection attempts

# Optional TLS configuration (not yet implemented)
# [network.tls]
# enabled = true
# ca_path = "/path/to/ca-cert.pem"
# skip_verify = false

[clipboard]
check_interval = "500ms"
max_size = 10485760  # 10MB
text_only = true
ignore_empty = true
bidirectional = true
# Add regex patterns to ignore certain clipboard content
# ignore_patterns = ["^password:", "^secret:"]

[logging]
level = "info"  # trace, debug, info, warn, error
format = "pretty"  # json, pretty, compact
# file = "/var/log/cursedboard/client.log"
# max_size = "10MB"
max_files = 5

# macOS-specific settings
[platform.macos]
use_universal_clipboard = false
# Monitor specific pasteboard types (default: all text types)
# pasteboard_types = ["public.utf8-plain-text", "public.rtf"]