# Complete configuration example for Linux
# Place this file at ~/.config/cursedboard/config.toml

[network]
bind_addr = "0.0.0.0"  # Listen on all interfaces
port = 34254
connection_timeout = "30s"

# Define peers to connect to (e.g., macOS machines)
[[network.peers]]
host = "192.168.1.100"  # macOS machine IP
name = "macbook"

# Add more peers as needed
# [[network.peers]]
# host = "192.168.1.101"
# name = "imac"

# Server doesn't need reconnect settings
[network.reconnect]
enabled = false

# Optional TLS configuration (not yet implemented)
# [network.tls]
# enabled = true
# cert_path = "/path/to/server-cert.pem"
# key_path = "/path/to/server-key.pem"
# ca_path = "/path/to/ca-cert.pem"  # For client verification

[clipboard]
check_interval = "500ms"
max_size = 10485760  # 10MB
text_only = true
ignore_empty = true
bidirectional = true
# Security: ignore sensitive patterns
ignore_patterns = [
    "^-----BEGIN.*KEY-----",  # Private keys
    "^password:",
    "^token:",
    "^secret:"
]

[logging]
level = "info"
format = "pretty"
# file = "/var/log/cursedboard/server.log"
# max_size = "50MB"
max_files = 10

# Linux-specific settings
[platform.linux]
selection = "clipboard"  # clipboard, primary, secondary
# display = ":0"  # X11 display (if not default)

# Wayland-specific settings
# [platform.linux.wayland]
# force_wayland = true